# Generated by Django 3.0.7 on 2021-12-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211219_2259'),
        ('movie', '0002_auto_20211219_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='users',
            field=models.ManyToManyField(to='accounts.User'),
        ),
    ]
