# Generated by Django 3.0.7 on 2021-12-31 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211219_2259'),
        ('movie', '0004_dislike_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dislike',
            new_name='MovieDislike',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='MovieLike',
        ),
    ]
