# Generated by Django 3.0.7 on 2021-12-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20211231_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielike',
            old_name='status',
            new_name='dislike',
        ),
        migrations.AddField(
            model_name='movielike',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MovieDislike',
        ),
    ]
