# Generated by Django 3.2.9 on 2021-12-12 06:41

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(default='')),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series')], max_length=15)),
                ('image', models.TextField()),
                ('video_file', models.TextField()),
                ('eps_num', models.IntegerField()),
                ('season_num', models.IntegerField()),
                ('show_start', models.DateField()),
                ('category', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
