# Generated by Django 3.2.9 on 2021-12-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
