# Generated by Django 3.2.9 on 2021-12-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_mylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='quality',
            field=models.CharField(choices=[('SD', 'SD'), ('HD', 'HD'), ('FHD', 'FHD'), ('BR', 'BR')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
