# Generated by Django 3.0.7 on 2021-12-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20211224_0238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
