# Generated by Django 3.0.7 on 2021-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211219_2259'),
        ('episode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='users',
            field=models.ManyToManyField(to='accounts.User'),
        ),
    ]
